services:

  qa-dev:

    build: .

    container_name: qa-dev

    restart: unless-stopped

    ports:
      - "2222:22"

    volumes:
      - .:/workspace

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - default
      - qa-net

    tty: true

  chrome:

    image: selenium/standalone-chrome@sha256:cd778b6f38d99d1e14a05a767f576aff2face98d5202a2192d857614c265ec4d

    container_name: selenium-chrome

    shm_size: 2gb

    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - .:/workspace
      - ./descargas:/home/seluser/descargas

  orchestrator-api:

    build:
      context: .
      dockerfile: orchestrator_api/Dockerfile

    container_name: orchestrator-api

    restart: unless-stopped

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - .:/workspace

    working_dir: /workspace

    networks:
      - default
      - qa-net

    depends_on:
      - chrome

networks:
  qa-net:
    external: true