services:

  qa-dev:

    build: .

    container_name: qa-dev

    restart: unless-stopped

    ports:
      - "2222:22"

    volumes:
      - .:/workspace

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - default
      - qa-net

    tty: true

  chrome:

    image: selenium/standalone-chrome:latest

    container_name: selenium-chrome

    shm_size: 2gb

    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - .:/workspace
      - ./descargas:/home/seluser/descargas

networks:
  qa-net:
    external: true